### ISSUE TITLE
API keys not accessible from getstream.js file

### ISSUE THREAD

**Issue by yuccayucca** [GetStream/stream-node-orm#24]
I've copied the getstream.js file into the root directory and filled in all the API keys info, but seems like the module cannot access this data. 

I've also tried creating a getstream.json as instructed [here](https://github.com/tbarbugli/stream-node) and adding the path to `STREAM_NODE_CONFIG_DIR` in the .env, but that doesn't work either.

Only way to make the module accept the keys was to enter them directly in config.default.js.

Is my configuration somehow incorrect? Please let me know what can be done to fix this.

**Comment by nparsons08** [comment]
@yuccayucca Happy to help resolve the issue you're experiencing. Can you contact support@getstream.io with an example of your `.env` file? That'll give us a better idea of what your code looks like. Thanks!

**Comment by nparsons08** [comment]
Closing this issue out due to inactivity. Please open a new issue or contact support@getstream.io if the issue persists.
