### ISSUE TITLE
Node 10?

### ISSUE THREAD

**Issue by wallymathieu** [GetStream/stream-node-orm#33]
Hi! Trying to test `getstream`. However, I can't install it due to:
```
The engine "node" is incompatible with this module. Expected version ">=4.8 <=9".
```

**Comment by dwightgunning** [comment]
Node 10.0 was released last week and we're still working through updates to our various integrations and demos. We'll get to this shortly. In the meantime you might consider running with the latest Node 9.x release which is supported.

**Comment by ruggi** [comment]
Closing this, confirmed working with Node 10.x

**Comment by wallymathieu** [comment]
Sweet 😀
