### ISSUE TITLE
require('getstream-node') throws exception

### ISSUE THREAD

**Issue by tiotdev** [GetStream/stream-node-orm#37]
I have a one-line test.js file:

```
require('getstream-node');
```

When running it with `node test.js`, I get this exception: `Error: secretOrPrivateKey must have a value`, requiring the getstream.js file and mongoose before doesn't help.

**Comment by ferhatelmas** [comment]
#40

**Comment by SeanDunford** [comment]
Just want to say that this error can be resolved by following instructions in readme. 

```
Step 2 - Config file
Copy getstream.js config file from node_modules/getstream-node into the root directory of your application Make sure you require the getstream-node early on in your application (eg. in app.js)
```
