### ISSUE TITLE
Breaking changes on getstream-js dependency

### ISSUE THREAD

**Issue by Stefkoff** [GetStream/stream-node-orm#39]
gestream-js had a braking changes since version 5.0.0 https://github.com/GetStream/stream-js/blob/master/CHANGELOG.md#500---2020-07-06

Now when require('getstream-node') it is throwing an exception for missing function connect: "stream.connect is not a function".

Thanks

**Comment by ferhatelmas** [comment]
Thanks for your report. We will adapt this package to use new version soon.
